// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Conversation(arg1) {
  return window['go']['main']['App']['Conversation'](arg1);
}

export function PostMessage(arg1, arg2) {
  return window['go']['main']['App']['PostMessage'](arg1, arg2);
}

export function RetryRun(arg1, arg2) {
  return window['go']['main']['App']['RetryRun'](arg1, arg2);
}

export function SaveAgent(arg1) {
  return window['go']['main']['App']['SaveAgent'](arg1);
}

export function SaveConversation(arg1) {
  return window['go']['main']['App']['SaveConversation'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Schedule(arg1) {
  return window['go']['main']['App']['Schedule'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SetAgentEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetAgentEnabled'](arg1, arg2);
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}

export function StartProbe(arg1, arg2) {
  return window['go']['main']['App']['StartProbe'](arg1, arg2);
}

export function StopChain(arg1) {
  return window['go']['main']['App']['StopChain'](arg1);
}

export function StopProbe(arg1) {
  return window['go']['main']['App']['StopProbe'](arg1);
}

export function StopRun(arg1) {
  return window['go']['main']['App']['StopRun'](arg1);
}

export function Workspace() {
  return window['go']['main']['App']['Workspace']();
}
