// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWebSource(arg1, arg2) {
  return window['go']['main']['App']['AddWebSource'](arg1, arg2);
}

export function ChooseWorkspaceDirectory() {
  return window['go']['main']['App']['ChooseWorkspaceDirectory']();
}

export function Conversation(arg1) {
  return window['go']['main']['App']['Conversation'](arg1);
}

export function DeleteModel(arg1, arg2) {
  return window['go']['main']['App']['DeleteModel'](arg1, arg2);
}

export function ExportVersion(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportVersion'](arg1, arg2, arg3);
}

export function ImportSkill() {
  return window['go']['main']['App']['ImportSkill']();
}

export function ImportSources(arg1) {
  return window['go']['main']['App']['ImportSources'](arg1);
}

export function ListWorkspaceFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListWorkspaceFiles'](arg1, arg2, arg3);
}

export function Models() {
  return window['go']['main']['App']['Models']();
}

export function OpenArtifact(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenArtifact'](arg1, arg2, arg3);
}

export function OpenSourceFile(arg1, arg2) {
  return window['go']['main']['App']['OpenSourceFile'](arg1, arg2);
}

export function OpenWorkspaceDirectory(arg1) {
  return window['go']['main']['App']['OpenWorkspaceDirectory'](arg1);
}

export function PostMessage(arg1, arg2) {
  return window['go']['main']['App']['PostMessage'](arg1, arg2);
}

export function ReadSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadSource'](arg1, arg2, arg3);
}

export function ReadWorkspaceFile(arg1, arg2) {
  return window['go']['main']['App']['ReadWorkspaceFile'](arg1, arg2);
}

export function RetryRun(arg1, arg2) {
  return window['go']['main']['App']['RetryRun'](arg1, arg2);
}

export function SaveAgent(arg1) {
  return window['go']['main']['App']['SaveAgent'](arg1);
}

export function SaveConversation(arg1) {
  return window['go']['main']['App']['SaveConversation'](arg1);
}

export function SaveModel(arg1) {
  return window['go']['main']['App']['SaveModel'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveSkill(arg1) {
  return window['go']['main']['App']['SaveSkill'](arg1);
}

export function Schedule(arg1) {
  return window['go']['main']['App']['Schedule'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SetAgentEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetAgentEnabled'](arg1, arg2);
}

export function SkillContent(arg1) {
  return window['go']['main']['App']['SkillContent'](arg1);
}

export function Skills() {
  return window['go']['main']['App']['Skills']();
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}

export function StartProbe(arg1, arg2) {
  return window['go']['main']['App']['StartProbe'](arg1, arg2);
}

export function StopChain(arg1) {
  return window['go']['main']['App']['StopChain'](arg1);
}

export function StopProbe(arg1) {
  return window['go']['main']['App']['StopProbe'](arg1);
}

export function StopRun(arg1) {
  return window['go']['main']['App']['StopRun'](arg1);
}

export function TestModel(arg1) {
  return window['go']['main']['App']['TestModel'](arg1);
}

export function Workspace() {
  return window['go']['main']['App']['Workspace']();
}
