// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {store} from '../models';

export function Conversation(arg1:string):Promise<app.ConversationDetail>;

export function PostMessage(arg1:string,arg2:string):Promise<store.Message>;

export function RetryRun(arg1:string,arg2:string):Promise<store.ConversationRun>;

export function SaveAgent(arg1:app.AgentInput):Promise<store.Agent>;

export function SaveConversation(arg1:store.Conversation):Promise<store.Conversation>;

export function SaveSettings(arg1:app.SettingsInput):Promise<app.SettingsView>;

export function Schedule(arg1:store.ScheduleRequest):Promise<store.Delivery>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<store.ConversationRun>;

export function SetAgentEnabled(arg1:string,arg2:boolean):Promise<store.Agent>;

export function Snapshot():Promise<app.Snapshot>;

export function StartProbe(arg1:string,arg2:string):Promise<store.ProbeRun>;

export function StopChain(arg1:string):Promise<void>;

export function StopProbe(arg1:string):Promise<void>;

export function StopRun(arg1:string):Promise<void>;

export function Workspace():Promise<app.Workspace>;
