// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {app} from '../models';
import {skill} from '../models';
import {material} from '../models';

export function AddWebSource(arg1:string,arg2:string):Promise<store.Source>;

export function ChooseWorkspaceDirectory():Promise<string>;

export function Conversation(arg1:string):Promise<app.ConversationDetail>;

export function DeleteModel(arg1:string,arg2:number):Promise<void>;

export function ExportVersion(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ImportSkill():Promise<skill.Bundle>;

export function ImportSources(arg1:string):Promise<app.ImportResult>;

export function ListWorkspaceFiles(arg1:string,arg2:string,arg3:number):Promise<material.WorkspacePage>;

export function Models():Promise<Array<store.ModelConfig>>;

export function OpenArtifact(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function OpenSourceFile(arg1:string,arg2:string):Promise<void>;

export function OpenWorkspaceDirectory(arg1:string):Promise<void>;

export function PostMessage(arg1:string,arg2:string):Promise<store.Message>;

export function ReadSource(arg1:string,arg2:string,arg3:number):Promise<store.SourcePage>;

export function ReadWorkspaceFile(arg1:string,arg2:string):Promise<store.SourcePage>;

export function RetryRun(arg1:string,arg2:string):Promise<store.ConversationRun>;

export function SaveAgent(arg1:app.AgentInput):Promise<store.Agent>;

export function SaveConversation(arg1:store.Conversation):Promise<store.Conversation>;

export function SaveModel(arg1:app.ModelInput):Promise<store.ModelConfig>;

export function SaveSettings(arg1:app.SettingsInput):Promise<app.SettingsView>;

export function SaveSkill(arg1:app.SkillInput):Promise<store.SkillContent>;

export function Schedule(arg1:store.ScheduleRequest):Promise<store.Delivery>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<store.ConversationRun>;

export function SetAgentEnabled(arg1:string,arg2:boolean):Promise<store.Agent>;

export function SkillContent(arg1:string):Promise<store.SkillContent>;

export function Skills():Promise<Array<store.Skill>>;

export function Snapshot():Promise<app.Snapshot>;

export function StartProbe(arg1:string,arg2:string):Promise<store.ProbeRun>;

export function StopChain(arg1:string):Promise<void>;

export function StopProbe(arg1:string):Promise<void>;

export function StopRun(arg1:string):Promise<void>;

export function TestModel(arg1:app.ModelInput):Promise<app.ConnectionResult>;

export function Workspace():Promise<app.Workspace>;
